### ISSUE TITLE
[Suggestion] Add a command or a statebag to lock status

### ISSUE THREAD

**Issue by Oldarorn** [esx-framework/esx_status#8]
The thing is, we can't actually avoid hunger/thirst to update in every situation, but we could be able to trigger something to lock our status for a time, it could be usefull when you're doing something out of Roleplay like furnishing your house when using some resources or anything else like this

**Comment by zizujr** [comment]
> The thing is, we can't actually avoid hunger/thirst to update in every situation, but we could be able to trigger something to lock our status for a time, it could be useful when you're doing something out of Roleplay like furnishing your house when using some resources or anything else like this

The thing is, this is roleplay. Meant to recreate IRL situations in every possible way... Realistically you can never just pause hunger/thirst... Each developer can update this to work for their needs! So that is up to you! (I wouldn't though knowing that would make this useless as players would just abuse it! ~ they always find a way xD)

**Comment by Gellipapa** [comment]
Yes, unfortunately you have to disable it individually, because it can cause a lot of errors if it is not reset, and many people would not use this feature.

You could simply write a logic that as long as the player is in the skin menu, you set the drink and food level to 100% every time.

Thanks for the suggestion but we will not implement something like that.
